 export const homeObject1 ={
     id:'about',
     lightBg:false,
     lightText:true,
     topLine:'premium Bank',
     headLine:'unlimited Transactions with zero feas',
     description:'Get access to our exclusive app that allows you to send unlimted transactions without getting charged any feas',
     buttonLable:'Get started',
     imgStart:false,
     img:require('../../images/svg-1.svg').default,
     alt:'car',
     primary:true,
     darkText:false,
 }
 export const homeObject2 ={
    id:'discover',
    lightBg:true,
    lightText:false,
    topLine:'premium Bank',
    headLine:'unlimited Transactions with zero feas',
    description:'Get access to our exclusive app that allows you to send unlimted transactions without getting charged any feas',
    buttonLable:'Get started',
    imgStart:true,
    img:require('../../images/svg-2.svg').default,
    alt:'car',
    primary:false,
    darkText:true,
}
export const homeObject3 ={
    id:'signup',
    lightBg:true,
    lightText:false,
    topLine:'premium Bank',
    headLine:'unlimited Transactions with zero feas',
    description:'Get access to our exclusive app that allows you to send unlimted transactions without getting charged any feas',
    buttonLable:'Sign Up',
    imgStart:false,
    img:require('../../images/svg-3.svg').default,
    alt:'car',
    primary:false,
    darkText:true,
}